"""Build the shipped grammar bank.

Written by hand rather than generated: grammar questions need a stated rule and
one defensible answer, and a model asked for 200 of them will produce plausible
items with two right answers. Each item carries the rule it tests so the app can
explain a wrong answer without an API call.
"""
import json

def q(level, topic, prompt, options, answer, why):
    assert options[answer], "answer index out of range"
    assert len(set(options)) == len(options), f"repeated option in: {prompt}"
    return {"lv": level, "t": topic, "q": prompt, "o": options, "a": answer, "w": why}

ITEMS = [
  # ── tenses ───────────────────────────────────────────────────────────────
  q('A2','Present simple','She ____ to work by bus every day.',['go','goes','going','gone'],1,
    'Third person singular in the present simple takes -s: he/she/it goes.'),
  q('A2','Present continuous','Be quiet — the baby ____.',['sleeps','is sleeping','slept','sleep'],1,
    'Something happening right now takes the present continuous: is + -ing.'),
  q('A2','Past simple','We ____ the match last Friday.',['win','won','have won','winning'],1,
    'A finished time ("last Friday") takes the past simple.'),
  q('B1','Present perfect','I ____ in this city since 2019.',['live','lived','have lived','am living'],2,
    '"Since" marks something starting in the past and still true: present perfect.'),
  q('B1','Present perfect vs past','____ you ever ____ to Japan?',['Did / go','Have / been','Have / went','Are / going'],1,
    'Life experience with no stated time takes the present perfect: have been.'),
  q('B1','Past continuous','I ____ dinner when the phone rang.',['cooked','was cooking','have cooked','cook'],1,
    'A longer action interrupted by a shorter one takes the past continuous.'),
  q('B1','Past perfect','By the time we arrived, the film ____.',['started','has started','had started','was starting'],2,
    'The earlier of two past events takes the past perfect: had started.'),
  q('B2','Future forms','Look at those clouds — it ____ rain.',['will','is going to','shall','would'],1,
    'Present evidence for a future event takes "going to", not "will".'),
  q('B2','Future perfect','By next June I ____ here for ten years.',['work','will work','will have worked','have worked'],2,
    'Completed before a future point: will have + past participle.'),
  q('B1','Present perfect continuous','My eyes hurt — I ____ at this screen all morning.',
    ['stare','have stared','have been staring','stared'],2,
    'An action continuing up to now, with the duration in focus, takes have been + -ing.'),

  # ── articles and determiners ──────────────────────────────────────────────
  q('A2','Articles','She is ____ engineer at a shipping firm.',['a','an','the','—'],1,
    '"An" before a vowel sound: an engineer.'),
  q('A2','Articles','____ sun rose at six.',['A','An','The','—'],2,
    'Unique things take "the": the sun, the moon, the earth.'),
  q('B1','Articles','I do not drink ____ coffee in the evening.',['a','the','—','an'],2,
    'An uncountable noun in a general sense takes no article.'),
  q('B1','Quantifiers','There is not ____ milk left.',['many','much','few','several'],1,
    '"Much" goes with uncountable nouns; "many" with countable ones.'),
  q('B1','Quantifiers','____ of my friends live abroad.',['Much','Every','Several','Little'],2,
    '"Several" takes a plural countable noun and a plural verb.'),
  q('B2','Quantifiers','She has ____ patience for excuses.',['few','a few','little','a little'],2,
    '"Little" (without "a") means almost none, and pairs with an uncountable noun.'),

  # ── prepositions ─────────────────────────────────────────────────────────
  q('A2','Prepositions','The meeting is ____ Monday morning.',['in','on','at','by'],1,
    'Days and dates take "on": on Monday.'),
  q('A2','Prepositions','We will be there ____ six o\'clock.',['in','on','at','to'],2,
    'Clock times take "at": at six o\'clock.'),
  q('B1','Prepositions','She has worked here ____ three years.',['since','for','from','during'],1,
    '"For" takes a length of time; "since" takes a starting point.'),
  q('B1','Prepositions','He is very good ____ explaining difficult ideas.',['in','on','at','for'],2,
    '"Good at" is the fixed pairing, and a verb after a preposition takes -ing.'),
  q('B2','Prepositions','The decision depends ____ the budget.',['of','on','to','from'],1,
    '"Depend" is always followed by "on".'),
  q('B2','Prepositions','I must apologise ____ being late.',['of','for','to','about'],1,
    'You apologise TO a person FOR a thing.'),

  # ── conditionals ─────────────────────────────────────────────────────────
  q('B1','First conditional','If it ____ tomorrow, we will stay in.',['rains','will rain','rained','would rain'],0,
    'First conditional: if + present simple, then will + infinitive. Never "will" in the if-clause.'),
  q('B2','Second conditional','If I ____ you, I would take the job.',['am','was','were','will be'],2,
    'The second conditional uses "were" for every person: if I were you.'),
  q('B2','Third conditional','If she ____ harder, she would have passed.',
    ['studied','had studied','would study','has studied'],1,
    'Third conditional: if + past perfect, then would have + past participle.'),
  q('C1','Mixed conditional','If I had taken that job, I ____ in Dhaka now.',
    ['would live','would have lived','will live','lived'],0,
    'A past condition with a present result: had + past participle, then would + infinitive.'),

  # ── modals ───────────────────────────────────────────────────────────────
  q('A2','Modals','You ____ smoke in the hospital.',['must not','do not must','not must','must not to'],0,
    'Modals take no auxiliary and no "to": must not smoke.'),
  q('B1','Modals','You ____ be tired after that journey.',['must','can','should','may not'],0,
    '"Must" expresses a confident deduction, not only obligation.'),
  q('B1','Modals','I ____ swim when I was six.',['can','could','was able','may'],1,
    '"Could" is the past of general ability.'),
  q('B2','Modals','She ____ the email — she never received it.',
    ['must have sent','cannot have sent','should send','might send'],1,
    '"Cannot have + past participle" expresses certainty that something did NOT happen.'),
  q('B2','Modals','You ____ told me — I would have helped.',
    ['should have','should','must have','ought'],0,
    '"Should have + past participle" is regret about the past.'),

  # ── passive and reported speech ──────────────────────────────────────────
  q('B1','Passive','The bridge ____ in 1890.',['built','was built','has built','is building'],1,
    'Passive past simple: was/were + past participle.'),
  q('B2','Passive','The results ____ tomorrow.',
    ['will announce','will be announced','are announcing','announce'],1,
    'The results receive the action, so the passive is needed: will be announced.'),
  q('B1','Reported speech','She said she ____ tired.',['is','was','has been','will be'],1,
    'Reported speech shifts the tense back one step: "I am" becomes "she was".'),
  q('B2','Reported speech','He asked me where ____.',
    ['do I live','I live','did I live','I lived'],3,
    'A reported question takes statement word order and a backshifted tense.'),

  # ── relative clauses and structure ───────────────────────────────────────
  q('B1','Relative clauses','The man ____ car was stolen called the police.',
    ['who','whose','which','whom'],1,
    '"Whose" marks possession: the man whose car.'),
  q('B2','Relative clauses','The book, ____ I read last year, is still my favourite.',
    ['that','which','what','who'],1,
    'A non-defining clause after a comma takes "which", never "that".'),
  q('B2','Gerund vs infinitive','I really enjoy ____ early.',['to get up','getting up','get up','got up'],1,
    '"Enjoy" is always followed by the -ing form.'),
  q('B2','Gerund vs infinitive','She agreed ____ the report by Friday.',
    ['finishing','to finish','finish','finished'],1,
    '"Agree" is followed by the infinitive with "to".'),
  q('B2','Gerund vs infinitive','I stopped ____ coffee because it kept me awake.',
    ['to drink','drinking','drink','drunk'],1,
    '"Stop + -ing" means you ended the habit; "stop to drink" means you paused in order to drink.'),
  q('C1','Inversion','Not only ____ late, but he also forgot the tickets.',
    ['he was','was he','he is','is he'],1,
    'A negative adverbial at the front inverts the subject and auxiliary: was he.'),

  # ── agreement, comparatives, word order ──────────────────────────────────
  q('A2','Comparatives','This exam was ____ than the last one.',
    ['difficult','more difficult','most difficult','difficulter'],1,
    'Adjectives of three or more syllables take "more", not "-er".'),
  q('A2','Superlatives','It is ____ film I have ever seen.',['the best','best','the better','better'],0,
    'A superlative takes "the": the best.'),
  q('B1','Subject–verb agreement','Each of the students ____ a folder.',['have','has','are having','were'],1,
    '"Each" is singular however many follow it, so the verb is singular.'),
  q('B1','Subject–verb agreement','The news ____ better today.',['are','is','have','were'],1,
    '"News" looks plural but takes a singular verb.'),
  q('B2','Subject–verb agreement','Neither the manager nor the staff ____ been told.',
    ['has','have','is','was'],1,
    'With "neither…nor", the verb agrees with the nearer subject: staff have.'),
  q('B1','Word order','She ____ goes to bed before midnight.',['never','not','no','nothing'],0,
    'Adverbs of frequency go before the main verb: she never goes.'),
  q('B2','Word order','I have ____ finished the first chapter.',['yet','already','still not','ever'],1,
    '"Already" is used in affirmative sentences; "yet" belongs in questions and negatives.'),

  # ── commonly confused ────────────────────────────────────────────────────
  q('B1','Confusables','The rain did not ____ our plans.',['effect','affect','affects','effects'],1,
    '"Affect" is the verb; "effect" is normally the noun.'),
  q('B1','Confusables','There are ____ chairs than people.',['less','fewer','little','least'],1,
    '"Fewer" for countable nouns, "less" for uncountable ones.'),
  q('B1','Confusables','____ going to be a long meeting.',['Its','It\'s','Its\'','Their'],1,
    '"It\'s" is "it is". "Its" without an apostrophe is the possessive.'),
  q('B2','Confusables','The company laid ____ two hundred workers.',['of','off','out','over'],1,
    '"Lay off" means to make redundant.'),
  q('B2','Confusables','I am looking forward to ____ from you.',['hear','hearing','heard','be hearing'],1,
    '"Looking forward to" ends in a preposition, so the verb takes -ing.'),
  q('C1','Confusables','The evidence ____ the theory.',
    ['comprises','compromises','corroborates','collaborates'],2,
    '"Corroborate" means to support with evidence; "collaborate" means to work together.'),

  # ══ added in the second pass ═════════════════════════════════════════════
  # The first bank had 54 items with seventeen topics carrying exactly one
  # question, so a Grammar round repeated itself inside two sittings. Every
  # topic below is filled out, and each context is chosen so that only one
  # option survives — the commonest way a grammar item goes wrong is a
  # distractor a native speaker would also accept.

  # ── present simple ───────────────────────────────────────────────────────
  q('A2','Present simple','Water ____ at one hundred degrees Celsius.',
    ['boil','boils','is boiling','boiled'],1,
    'A general fact takes the present simple, with -s after a singular subject.'),
  q('A2','Present simple','My brother ____ like coffee at all.',
    ["doesn't","don't","isn't","not"],0,
    'Present simple negatives take does not after he, she or it.'),
  q('A2','Present simple','____ your parents live nearby?',
    ['Does','Do','Are','Is'],1,
    '"Parents" is plural, so the question takes the auxiliary "do".'),
  q('A2','Present simple','She rarely ____ television during the week.',
    ['watch','watches','watching','is watch'],1,
    'An adverb of frequency does not remove the -s ending: she watches.'),

  # ── present continuous ───────────────────────────────────────────────────
  q('A2','Present continuous','Where is Mia? She ____ in the garden.',
    ['works','is working','work','worked'],1,
    'Something in progress at this moment takes is + -ing.'),
  q('A2','Present continuous','I ____ my keys right now — have you seen them?',
    ['look for','am looking for','looked for','looks for'],1,
    'A search happening at the moment of speaking takes the present continuous.'),
  q('B1','Present continuous','You ____ always ____ my sentences!',
    ['do / finish','are / finishing','have / finished','were / finishing'],1,
    'The present continuous with "always" complains about a repeated habit.'),
  q('B1','Present continuous','Do not disturb her — she ____ for tomorrow’s viva.',
    ['revises','is revising','revised','has revised'],1,
    'An activity in progress right now takes is + -ing.'),

  # ── past simple ──────────────────────────────────────────────────────────
  q('A2','Past simple','She ____ born in Chattogram.',
    ['is','was','were','has been'],1,
    '"Be born" about one person in the past takes "was".'),
  q('A2','Past simple','They ____ not come to the wedding.',
    ['did','do','were','have'],0,
    'The past simple negative is did not followed by the base verb.'),
  q('B1','Past simple','When ____ you ____ your first job?',
    ['did / get','have / got','did / got','were / getting'],0,
    'After "did" the verb returns to its base form: did you get.'),
  q('A2','Past simple','I ____ my homework before dinner yesterday.',
    ['finish','finished','have finished','finishing'],1,
    '"Yesterday" is a finished time, so the past simple is used.'),

  # ── present perfect ──────────────────────────────────────────────────────
  q('B1','Present perfect','She ____ just ____ the report.',
    ['has / finished','have / finished','is / finishing','had / finished'],0,
    '"Just", with the result still standing, takes has + past participle.'),
  q('B1','Present perfect','I ____ never ____ such a beautiful sunset.',
    ['have / seen','have / saw','had / seen','did / see'],0,
    'Life experience with "never" takes the present perfect: have seen.'),
  q('B1','Present perfect','We ____ known each other for twenty years.',
    ['are','have','had','were'],1,
    '"For" plus a period reaching the present takes have known.'),
  q('B2','Present perfect','____ you finished the assignment yet?',
    ['Did','Have','Are','Were'],1,
    '"Yet" in a question belongs with the present perfect.'),

  # ── present perfect vs past ──────────────────────────────────────────────
  q('B1','Present perfect vs past','I ____ my wallet, so I cannot pay for this.',
    ['lost','have lost','was losing','had lost'],1,
    'The loss still matters now, which is what the present perfect marks.'),
  q('B1','Present perfect vs past','Shakespeare ____ thirty-seven plays.',
    ['has written','wrote','has been writing','writes'],1,
    'A life that has ended takes the past simple, however famous the result.'),
  q('B1','Present perfect vs past','I ____ him at the conference last March.',
    ['have met','met','have been meeting','had met'],1,
    '"Last March" states a finished time, which rules out the present perfect.'),
  q('B2','Present perfect vs past','She ____ in three countries so far.',
    ['worked','has worked','was working','had worked'],1,
    '"So far" marks a period still running, so the present perfect is used.'),

  # ── past continuous ──────────────────────────────────────────────────────
  q('B1','Past continuous','What ____ you ____ at eight o’clock last night?',
    ['did / do','were / doing','have / done','are / doing'],1,
    'An action in progress at a stated past moment takes was/were + -ing.'),
  q('B1','Past continuous','While she ____, someone knocked at the door.',
    ['studies','was studying','had studied','studied'],1,
    'The longer background action takes the past continuous.'),
  q('B1','Past continuous','They ____ not ____ attention when the announcement came.',
    ['did / paying','were / paying','have / paid','are / paying'],1,
    'The past continuous negative is was/were not followed by -ing.'),
  q('B2','Past continuous','It ____ heavily all afternoon, so we called the trip off.',
    ['rained','was raining','has rained','rains'],1,
    'Conditions running through a past period take the past continuous.'),

  # ── past perfect ─────────────────────────────────────────────────────────
  q('B2','Past perfect','She told me she ____ the email that morning.',
    ['sends','sent','had sent','has sent'],2,
    'An event earlier than the moment being reported takes the past perfect.'),
  q('B2','Past perfect','I did not recognise him because he ____ his beard.',
    ['shaves','shaved','has shaved','had shaved'],3,
    'The shaving came before the failure to recognise, so it takes had + participle.'),
  q('B2','Past perfect','After they ____ the contract, work began on site.',
    ['sign','signed','had signed','have signed'],2,
    '"After" with two past events puts the earlier one in the past perfect.'),
  q('C1','Past perfect','No sooner ____ she arrived than the power went out.',
    ['has','had','did','was'],1,
    '"No sooner … than" takes the past perfect, inverted: had she arrived.'),

  # ── future forms ─────────────────────────────────────────────────────────
  q('B1','Future forms','I ____ you tomorrow, I promise.',
    ['call','am calling','will call','was calling'],2,
    'A promise made as you speak takes "will".'),
  q('B1','Future forms','We ____ dinner with the Rahmans on Friday — it is all arranged.',
    ['will have','are having','have','had'],1,
    'A fixed personal arrangement takes the present continuous.'),
  q('B2','Future forms','This time next week I ____ on a beach.',
    ['will lie','will be lying','lie','am lying'],1,
    'An action in progress at a future moment takes will be + -ing.'),
  q('B1','Future forms','She has already decided: she ____ medicine.',
    ['will study','is going to study','studies','studied'],1,
    'An intention decided before speaking takes "going to".'),

  # ── future perfect ───────────────────────────────────────────────────────
  q('B2','Future perfect','By the time you read this, I ____.',
    ['leave','will leave','will have left','have left'],2,
    'Finished before a future point: will have + past participle.'),
  q('B2','Future perfect','____ they ____ the bridge by December?',
    ['Will / finish','Will / have finished','Do / finish','Have / finished'],1,
    '"By December" asks about completion, which takes the future perfect.'),
  q('C1','Future perfect','In August we ____ married for fifty years.',
    ['will be','will have been','are','have been'],1,
    'A duration complete at a future point takes will have been.'),
  q('B2','Future perfect','I ____ the whole series by the weekend.',
    ['watch','will watch','will have watched','have watched'],2,
    '"By the weekend" sets a future deadline, so the future perfect is used.'),

  # ── present perfect continuous ───────────────────────────────────────────
  q('B2','Present perfect continuous','She ____ for the exam since March.',
    ['prepares','has prepared','has been preparing','is preparing'],2,
    'An activity running from a past point up to now takes has been + -ing.'),
  q('B2','Present perfect continuous','The roads are soaked — it ____.',
    ['rains','has rained','has been raining','rained'],2,
    'Present evidence of an activity only just stopping takes has been + -ing.'),
  q('B2','Present perfect continuous','My hands are covered in paint — I ____ the kitchen.',
    ['painted','have painted','have been painting','paint'],2,
    'The focus is the activity that left the traces, not a finished result.'),
  q('B2','Present perfect continuous','They ____ about the same clause all morning and still have not agreed.',
    ['argue','have argued','have been arguing','are arguing'],2,
    'An unfinished activity through a period reaching now takes have been + -ing.'),

  # ── conditionals ─────────────────────────────────────────────────────────
  q('B1','First conditional','If it ____ tomorrow, we will move the ceremony indoors.',
    ['will rain','rains','rained','would rain'],1,
    'The "if" half of a first conditional uses the present simple, never "will".'),
  q('B1','First conditional','You will miss the bus unless you ____ now.',
    ['will leave','leave','left','would leave'],1,
    '"Unless" behaves like "if not" and takes the present simple.'),
  q('B1','First conditional','If she ____ the deadline, the client ____ the contract.',
    ['misses / will cancel','will miss / cancels','missed / would cancel','misses / cancelled'],0,
    'First conditional: present simple in the if-clause, will in the other.'),
  q('B2','First conditional','I ____ you as soon as the results ____ out.',
    ['will tell / come','tell / will come','would tell / came','will tell / will come'],0,
    'After "as soon as" the present simple already carries future meaning.'),

  q('B2','Second conditional','If I ____ you, I would take the offer.',
    ['am','was','were','will be'],2,
    'The second conditional uses "were" for every subject: if I were you.'),
  q('B2','Second conditional','If we ____ more time, we ____ the whole coast.',
    ['have / will see','had / would see','had / will see','have / would see'],1,
    'Second conditional: past simple in the if-clause, would in the other.'),
  q('B2','Second conditional','She would travel more if she ____ the money.',
    ['has','had','would have','will have'],1,
    'The if-clause of a second conditional takes the past simple.'),
  q('B2','Second conditional','What ____ you do if the visa ____ refused?',
    ['will / is','would / were','would / is','will / were'],1,
    'An unlikely situation takes would in the main clause and the past in the other.'),

  q('B2','Third conditional','If she ____ earlier, she would have caught the train.',
    ['left','had left','has left','would leave'],1,
    'The third conditional uses the past perfect in the if-clause.'),
  q('B2','Third conditional','We ____ the flight if the road had been clear.',
    ['would catch','would have caught','had caught','will catch'],1,
    'The main clause of a third conditional is would have + past participle.'),
  q('C1','Third conditional','Had I known about the strike, I ____ another route.',
    ['took','would take','would have taken','had taken'],2,
    '"Had I known" is an inverted third conditional; the result is would have taken.'),
  q('B2','Third conditional','If they ____ the warning, nobody ____ hurt.',
    ['heeded / would be','had heeded / would have been','heed / will be','had heeded / would be'],1,
    'Both halves look back: past perfect, then would have been.'),

  q('C1','Mixed conditional','If I had studied medicine, I ____ a doctor now.',
    ['would be','would have been','will be','am'],0,
    'A past cause with a present result takes past perfect, then would + base verb.'),
  q('C1','Mixed conditional','If she ____ so stubborn, she would have accepted the help.',
    ['was not','were not','had not been','is not'],1,
    'A lasting trait behind a past result keeps the second-conditional "were not".'),
  q('C1','Mixed conditional','I ____ the train if I were not always so late.',
    ['would not miss','would not have missed','did not miss','will not miss'],1,
    'A present habit explaining a past event takes would not have missed.'),
  q('C1','Mixed conditional','If he had taken the job, he ____ in Dhaka today.',
    ['lived','would live','would have lived','lives'],1,
    'The condition is past, the result is now, so the result takes would + base verb.'),

  # ── inversion ────────────────────────────────────────────────────────────
  q('C1','Inversion','Never ____ such a badly argued paper.',
    ['I have read','have I read','I read','did I have read'],1,
    'A negative adverb at the front pulls the auxiliary before the subject.'),
  q('C1','Inversion','Not only ____ the deadline, he apologised for it.',
    ['he missed','did he miss','he did miss','missed he'],1,
    '"Not only" at the front of a clause forces did + subject + base verb.'),
  q('C1','Inversion','Rarely ____ a decision reversed so quickly.',
    ['we see','do we see','we do see','see we'],1,
    '"Rarely" in front position inverts the subject and the auxiliary.'),
  q('C1','Inversion','Only after the audit ____ the scale of the loss.',
    ['they understood','did they understand','they did understand','understood they'],1,
    '"Only after" delays the clause and inverts it: did they understand.'),

  # ── comparatives and superlatives ────────────────────────────────────────
  q('A2','Comparatives','This route is ____ than the one through the city.',
    ['quick','quicker','quickest','more quick'],1,
    'A one-syllable adjective forms its comparative with -er, not "more".'),
  q('B1','Comparatives','The second draft was far ____ than the first.',
    ['convincing','more convincing','most convincing','convincinger'],1,
    'A three-syllable adjective takes "more", and "far" only intensifies it.'),
  q('B1','Comparatives','The more you practise, ____ it gets.',
    ['easier','the easier','the easiest','more easy'],1,
    'The "the more … the more" pattern needs "the" in front of both halves.'),
  q('B2','Comparatives','Her handwriting is no ____ than mine.',
    ['neat','neater','neatest','more neat'],1,
    '"No" before a comparative compares two things: no neater than mine.'),

  q('A2','Superlatives','It is ____ building in the district.',
    ['taller','the tallest','tallest','the taller'],1,
    'A superlative takes "the": the tallest building.'),
  q('B1','Superlatives','That was ____ meal I have ever eaten.',
    ['the best','the better','best','the goodest'],0,
    '"Good" is irregular, and the superlative still takes "the": the best.'),
  q('B1','Superlatives','This is one of ____ questions on the paper.',
    ['the hardest','the harder','hardest','more hard'],0,
    '"One of" is followed by a plural noun with a superlative: one of the hardest.'),
  q('B2','Superlatives','She is by far ____ candidate we interviewed.',
    ['the strong','stronger','the strongest','most strong'],2,
    '"By far" intensifies a superlative, which still needs "the".'),

  # ── articles and quantifiers ─────────────────────────────────────────────
  q('A2','Articles','I saw ____ cat on the wall. ____ cat was asleep.',
    ['a / A','a / The','the / A','an / The'],1,
    'First mention takes "a"; the second mention is known, so it takes "the".'),
  q('B1','Articles','She plays ____ violin in ____ national orchestra.',
    ['a / an','the / the','— / the','the / a'],1,
    'Instruments take "the", and a single named orchestra takes "the".'),
  q('B1','Articles','____ honesty is what the job needs most.',
    ['A','An','The','—'],3,
    'An abstract noun used in general takes no article at all.'),

  q('A2','Quantifiers','There is not ____ sugar left in the jar.',
    ['many','much','a few','several'],1,
    '"Sugar" is uncountable, so the quantifier is "much".'),
  q('B1','Quantifiers','____ of the students had finished, so we waited.',
    ['A few','Few','Little','A little'],1,
    '"Few" without "a" means almost none, which is why they waited.'),
  q('B1','Quantifiers','We have ____ time — there is no need to run.',
    ['a little','little','a few','few'],0,
    '"A little" means some, and it is what makes running unnecessary.'),

  # ── countable and uncountable ────────────────────────────────────────────
  q('A2','Countable and uncountable','Could you give me ____ advice?',
    ['an','a','some','a few'],2,
    '"Advice" is uncountable, so it takes "some" and never "an".'),
  q('B1','Countable and uncountable','How ____ luggage are you taking?',
    ['many','much','many pieces','a lot'],1,
    '"Luggage" is uncountable, so the question word is "how much".'),
  q('B1','Countable and uncountable','She gave me two useful ____ of information.',
    ['pieces','piece','informations','information'],0,
    '"Information" cannot be counted directly; you count pieces of it.'),
  q('B1','Countable and uncountable','The ____ in this room is unbearable.',
    ['noises','noise','a noise','noisy'],1,
    'Used generally, "noise" is uncountable and takes no plural or article.'),
  q('B2','Countable and uncountable','He has made good ____ this term.',
    ['progresses','a progress','progress','progressions'],2,
    '"Progress" is uncountable, so it takes neither a plural nor "a".'),

  # ── gerund and infinitive ────────────────────────────────────────────────
  q('B1','Gerund vs infinitive','She avoided ____ the question directly.',
    ['answer','to answer','answering','answered'],2,
    '"Avoid" is always followed by the -ing form.'),
  q('B1','Gerund vs infinitive','They agreed ____ the deadline by a week.',
    ['extend','to extend','extending','extended'],1,
    '"Agree" takes the to-infinitive.'),
  q('B2','Gerund vs infinitive','On the way home she stopped ____ petrol.',
    ['getting','to get','get','got'],1,
    '"Stop to" states the purpose of stopping; "stop -ing" would end a habit.'),
  q('B2','Gerund vs infinitive','Remember ____ the gas before you leave.',
    ['turning off','to turn off','turn off','turned off'],1,
    '"Remember to" is a future duty; "remember -ing" is a memory.'),

  # ── subject–verb agreement ───────────────────────────────────────────────
  q('B1','Subject–verb agreement','Each of the applicants ____ a written test.',
    ['sit','sits','are sitting','have sat'],1,
    '"Each" is singular however plural the phrase after it looks.'),
  q('B1','Subject–verb agreement','The news ____ better than we expected.',
    ['were','was','have been','are'],1,
    '"News" ends in -s but is singular.'),
  q('B2','Subject–verb agreement','Either the twins or their mother ____ collecting them.',
    ['are','is','were','have'],1,
    'With "either … or" the verb agrees with the nearer subject: mother is.'),
  q('B2','Subject–verb agreement','A number of students ____ still waiting outside.',
    ['is','are','has','was'],1,
    '"A number of" is plural; only "the number of" takes a singular verb.'),

  # ── passive ──────────────────────────────────────────────────────────────
  q('B1','Passive','The bridge ____ in 1962.',
    ['built','was built','has built','is building'],1,
    'The bridge did not act, so the past passive is used: was built.'),
  q('B2','Passive','The results ____ by the end of the week.',
    ['will announce','will be announced','are announcing','announce'],1,
    'The future passive is will be + past participle.'),
  q('B2','Passive','My laptop ____ while I was at lunch.',
    ['stole','was stolen','has stolen','stealing'],1,
    'The laptop is the thing acted upon, so the verb is passive.'),
  q('C1','Passive','The proposal is believed ____ by the board already.',
    ['to approve','to have been approved','approving','approved'],1,
    'A completed passive after "believed" takes to have been + past participle.'),
  q('B2','Passive','This form ____ in black ink.',
    ['must complete','must be completed','must completing','completes'],1,
    'A modal passive is modal + be + past participle.'),

  # ── reported speech ──────────────────────────────────────────────────────
  q('B1','Reported speech','He said he ____ tired.',
    ['is','was','has been','will be'],1,
    'Reporting in the past shifts the present back one tense: is becomes was.'),
  q('B2','Reported speech','She asked me where I ____.',
    ['do live','did I live','lived','was I living'],2,
    'A reported question keeps statement word order and drops the auxiliary.'),
  q('B2','Reported speech','They told us ____ during the recording.',
    ['do not talk','not to talk','that not talk','no talking'],1,
    'A reported instruction takes told + object + (not) to + base verb.'),
  q('B2','Reported speech','He said he ____ finish it the following day.',
    ['will','would','shall','is going to'],1,
    'In reported speech "will" becomes "would".'),
  q('C1','Reported speech','She admitted ____ the message.',
    ['to delete','deleting','delete','that deleted'],1,
    '"Admit" is followed by the -ing form.'),

  # ── relative clauses ─────────────────────────────────────────────────────
  q('B1','Relative clauses','The woman ____ car was towed is at the desk.',
    ['who','whose','which','that'],1,
    'Possession inside a relative clause takes "whose".'),
  q('B2','Relative clauses','My sister, ____ lives in Sylhet, is visiting.',
    ['that','who','which','whom'],1,
    'A non-defining clause about a person takes "who", never "that".'),
  q('B2','Relative clauses','The report ____ we discussed has been withdrawn.',
    ['what','which','who','whose'],1,
    '"What" cannot introduce a relative clause; the thing is picked up by "which".'),
  q('C1','Relative clauses','The village in ____ she grew up has since flooded.',
    ['that','which','where','what'],1,
    'After a preposition the relative pronoun must be "which" or "whom".'),
  q('B2','Relative clauses','Everything ____ could go wrong did.',
    ['what','which','that','who'],2,
    'After "everything" the relative pronoun is "that", not "what".'),

  # ── word order ───────────────────────────────────────────────────────────
  q('A2','Word order','She ____ late for the meeting.',
    ['is never','never is','is not never','never'],0,
    'An adverb of frequency goes after "be": she is never late.'),
  q('B1','Word order','I ____ finished the first chapter.',
    ['already have','have already','have finished already the','already finished have'],1,
    '"Already" sits between the auxiliary and the main verb.'),
  q('B2','Word order','He speaks ____.',
    ['fluently English','English fluently','fluently the English','English fluent'],1,
    'The object comes before the manner adverb: speaks English fluently.'),
  q('B2','Word order','Could you tell me ____?',
    ['where is the office','where the office is','where is office','the office where is'],1,
    'An indirect question keeps statement order: where the office is.'),

  # ── adjective order ──────────────────────────────────────────────────────
  q('B1','Adjective order','She bought a ____ table.',
    ['wooden round small','small round wooden','round small wooden','wooden small round'],1,
    'English orders adjectives size, then shape, then material.'),
  q('B1','Adjective order','They live in a ____ house.',
    ['brick old lovely','lovely old brick','old lovely brick','brick lovely old'],1,
    'Opinion comes first, then age, then material: lovely old brick.'),
  q('B2','Adjective order','He wore a ____ jacket.',
    ['leather black long','long black leather','black long leather','leather long black'],1,
    'Length, then colour, then material: long black leather.'),
  q('B1','Adjective order','A ____ vase stood on the shelf.',
    ['Chinese tall blue','tall blue Chinese','blue tall Chinese','Chinese blue tall'],1,
    'Size, then colour, then origin: tall blue Chinese.'),

  # ── question tags ────────────────────────────────────────────────────────
  q('B1','Question tags','You have met her before, ____?',
    ["haven't you","have you","didn't you","don't you"],0,
    'A positive statement takes a negative tag repeating the same auxiliary.'),
  q('B1','Question tags','She is not coming, ____?',
    ['is she',"isn't she",'does she','will she'],0,
    'A negative statement takes a positive tag.'),
  q('B2','Question tags','Let us start, ____?',
    ['will we','shall we',"don't we","won't we"],1,
    'A "let us" suggestion always takes the tag "shall we".'),
  q('B2','Question tags','Nobody phoned, ____?',
    ['did they',"didn't they",'did he','were they'],0,
    '"Nobody" is negative, so the tag is positive, and it takes "they".'),
  q('B2','Question tags','Pass me the file, ____?',
    ['do you','will you','are you','shall you'],1,
    'A request in the imperative takes the tag "will you".'),

  # ── used to and would ────────────────────────────────────────────────────
  q('B1','Used to and would','I ____ swim every morning before work.',
    ['use to','used to','am used to','was used to'],1,
    'A past habit that has stopped takes "used to" with a d.'),
  q('B1','Used to and would','Did you ____ live in Khulna?',
    ['used to','use to','be used to','using to'],1,
    'After "did", "used to" loses its d: did you use to live.'),
  q('B2','Used to and would','I am not ____ working nights yet.',
    ['used to','use to','used','using to'],0,
    '"Be used to" means accustomed to, and is followed by -ing.'),
  q('B2','Used to and would','Every summer we ____ walk to the lake after dinner.',
    ['would','used','will','are used to'],0,
    '"Would" narrates a repeated past action, though not a past state.'),
  q('B2','Used to and would','She ____ have long hair when she was at school.',
    ['would','used to','is used to','uses to'],1,
    'A past state takes "used to"; "would" works only for repeated actions.'),

  # ── wish and regret ──────────────────────────────────────────────────────
  q('B2','Wish and regret','I wish I ____ more sleep last night.',
    ['had','have had','had had','would have'],2,
    'A regret about the past takes wish + past perfect.'),
  q('B2','Wish and regret','I wish it ____ so humid here.',
    ['is not','were not','had not been','will not be'],1,
    'A wish about now takes the past form, and "were" for every subject.'),
  q('B2','Wish and regret','I wish you ____ interrupting me.',
    ['stop','stopped','would stop','had stopped'],2,
    '"Wish + would" complains about someone else’s current behaviour.'),
  q('C1','Wish and regret','If only she ____ us before signing.',
    ['asked','had asked','asks','would ask'],1,
    '"If only" about the past takes the past perfect, like "wish".'),
  q('B2','Wish and regret','He regrets ____ the offer.',
    ['to turn down','turning down','turn down','turned down'],1,
    '"Regret + -ing" is about something already done.'),

  # ── so, such, enough, too ────────────────────────────────────────────────
  q('B1','So, such, enough, too','It was ____ a long queue that we gave up.',
    ['so','such','too','very'],1,
    '"Such" goes before a noun phrase; "so" goes before a bare adjective.'),
  q('B1','So, such, enough, too','The room was ____ small for all of us.',
    ['too','so','such','enough'],0,
    '"Too" means more than is acceptable, which is why it did not work.'),
  q('B1','So, such, enough, too','She is not old ____ to vote.',
    ['too','enough','so','such'],1,
    '"Enough" follows the adjective it limits: old enough.'),
  q('B2','So, such, enough, too','There were ____ many applicants that we extended the shortlist.',
    ['such','so','too','very'],1,
    'Before "many" the intensifier is "so", not "such".'),
  q('B2','So, such, enough, too','He spoke ____ quietly for anyone at the back to hear.',
    ['so','such','too','enough'],2,
    '"Too … for … to" says the degree defeated the purpose.'),

  # ── linking words ────────────────────────────────────────────────────────
  q('B1','Linking words','It rained all day; ____, the match went ahead.',
    ['however','moreover','therefore','because'],0,
    '"However" marks a contrast with what came before.'),
  q('B2','Linking words','____ the delay, the crew finished on schedule.',
    ['Although','Despite','However','Because'],1,
    '"Despite" is followed by a noun; "although" needs a full clause.'),
  q('B2','Linking words','____ the road was closed, we took the ferry.',
    ['Despite','In spite of','Since','Due to'],2,
    '"Since", meaning because, introduces a clause with a subject and a verb.'),
  q('B2','Linking words','The figures were wrong; ____, the whole forecast collapsed.',
    ['nevertheless','consequently','otherwise','meanwhile'],1,
    '"Consequently" introduces the result of what came before.'),
  q('C1','Linking words','Print the ticket, ____ you will not be let in.',
    ['therefore','otherwise','however','whereas'],1,
    '"Otherwise" states what follows if the instruction is ignored.'),

  # ── phrasal verbs ────────────────────────────────────────────────────────
  q('B1','Phrasal verbs','The meeting was ____ until Thursday.',
    ['put off','put on','put up','put out'],0,
    '"Put off" means to postpone.'),
  q('B1','Phrasal verbs','I cannot ____ this noise any longer.',
    ['put up with','put down to','put out of','put away with'],0,
    '"Put up with" means to tolerate.'),
  q('B2','Phrasal verbs','Sales ____ sharply after the price rise.',
    ['took off','fell through','dropped off','came round'],2,
    '"Drop off" means to decline; "take off" would mean the opposite.'),
  q('B2','Phrasal verbs','The deal ____ at the last minute.',
    ['fell through','fell out','fell over','fell for'],0,
    '"Fall through" means to collapse before completion.'),
  q('B2','Phrasal verbs','She ____ smoking three years ago.',
    ['gave in','gave up','gave away','gave off'],1,
    '"Give up" means to stop doing something.'),
  q('C1','Phrasal verbs','We need to ____ the figures before the audit.',
    ['go over','go off','go through with','go down'],0,
    '"Go over" means to examine carefully.'),

  # ── participle clauses ───────────────────────────────────────────────────
  q('C1','Participle clauses','____ the report, she noticed two errors.',
    ['Reading','Read','To read','Having read'],3,
    'An action finished before the main one takes "having" + past participle.'),
  q('B2','Participle clauses','____ in 1890, the building is now protected.',
    ['Building','Built','Having built','To build'],1,
    'A passive participle clause uses the past participle alone: built in 1890.'),
  q('B2','Participle clauses','____ the door, he realised he had left the keys inside.',
    ['Closing','Closed','To close','Having closing'],0,
    'Two actions at nearly the same moment take the -ing participle.'),
  q('C1','Participle clauses','Not ____ the language, she relied on gestures.',
    ['speak','speaking','spoken','to speak'],1,
    'A negative participle clause is "not" followed by the -ing form.'),
  q('C1','Participle clauses','____ by the noise, the birds scattered.',
    ['Startling','Startled','Having startled','To startle'],1,
    'The birds received the action, so the participle is passive: startled.'),
]

# integrity: no duplicate prompts, every answer in range, every item explained
seen = set()
for it in ITEMS:
    assert it['q'] not in seen, f"duplicate prompt: {it['q']}"
    seen.add(it['q'])
    assert 0 <= it['a'] < len(it['o'])
    assert len(it['w']) > 25, f"weak explanation: {it['q']}"
    assert len(it['o']) == 4, f"not four options: {it['q']}"

from collections import Counter
per_topic = Counter(i['t'] for i in ITEMS)
thin = {t: n for t, n in per_topic.items() if n < 4}
assert not thin, f"topics too thin to practise without repeating: {thin}"
for it in ITEMS:
    assert '____' in it['q'], f"nothing to fill in: {it['q']}"

topics = sorted({i['t'] for i in ITEMS})
levels = sorted({i['lv'] for i in ITEMS})
out = {'count': len(ITEMS), 'topics': topics, 'levels': levels, 'items': ITEMS}
with open('data/grammar/bank.json', 'w', encoding='utf-8') as f:
    json.dump(out, f, ensure_ascii=False)
print(f"{len(ITEMS)} grammar items across {len(topics)} topics, levels {levels}")
for lv in levels:
    print(' ', lv, sum(1 for i in ITEMS if i['lv'] == lv))
